FROM payara/micro
RUN wget -O /opt/payara/database-connector.jar https://jdbc.postgresql.org/download/postgresql-42.2.2.jar

ADD CsvProject.war /opt/payara
ADD connectionPool.txt /opt/payara
  
ENTRYPOINT ["java", "-jar", "/opt/payara/payara-micro.jar", "--addJars", "/opt/payara/database-connector.jar", "--postbootcommandfile", "connectionPool.txt", "--deploy", "/opt/payara/CsvProject.war"]
#ENTRYPOINT /bin/sh


