version: '3'
services:
  web:
    build: .
    depends_on:
      - postgres
    ports:
      - "8070:8080"
  postgres:
    build:
     context: .
     dockerfile: dockerfilePostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tpiPassword
      POSTGRES_USER: tpi
      POSTGRES_DB: tpiTest
