version: '3'
services:
  web:
    build: ./payara/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    build: 
     context: ./postgres
     dockerfile: dockerfilePostgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tpiPassword
      POSTGRES_USER: tpi
      POSTGRES_DB: tpitest
volumes:
  pgdata:
